#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from datetime import datetime, timezone
from typing import Any

UNIT_TYPES = ["infantry", "cavalry", "artillery"]
FIELDS = [
  "base",
  "attackingFromHigherElevation",
  "attackingFromLowerElevation",
  "attackingAcrossRiver",
  "attackingInForest",
  "attackingInPlains",
  "attackingFromFront",
  "attackingFromSide",
  "attackingFromRear",
]


def _as_number(value: Any) -> float | None:
  if isinstance(value, (int, float)) and not isinstance(value, bool):
    return float(value)
  return None


def validate_damage_matrix(candidate: Any) -> dict[str, Any] | None:
  if not isinstance(candidate, dict):
    return None

  for attacker in UNIT_TYPES:
    row = candidate.get(attacker)
    if not isinstance(row, dict):
      return None
    for defender in UNIT_TYPES:
      pair = row.get(defender)
      if not isinstance(pair, dict):
        return None
      for mode in ("ranged", "melee"):
        cell = pair.get(mode)
        if not isinstance(cell, dict):
          return None
        for field in FIELDS:
          if _as_number(cell.get(field)) is None:
            return None

  return candidate


def _piece_label(piece_type: str) -> str:
  return {"infantry": "Infantry", "cavalry": "Cavalry", "artillery": "Artillery"}.get(piece_type, piece_type)


def _format_base_cell(matrix: dict[str, Any], attacker: str, defender: str) -> str:
  pair = matrix[attacker][defender]
  ranged = int(float(pair["ranged"]["base"]))
  melee = int(float(pair["melee"]["base"]))
  return f"{ranged} / {melee}"


def render_markdown(matrix: dict[str, Any]) -> str:
  updated = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")

  base_head = ["Attacker \\ Defender"] + [f"{_piece_label(t)} (R/M)" for t in UNIT_TYPES]
  base_div = ["---"] * len(base_head)
  base_rows = []
  for attacker in UNIT_TYPES:
    base_rows.append([_piece_label(attacker)] + [_format_base_cell(matrix, attacker, defender) for defender in UNIT_TYPES])

  base_table_lines = [
    "| " + " | ".join(base_head) + " |",
    "| " + " | ".join(base_div) + " |",
    *["| " + " | ".join(row) + " |" for row in base_rows],
  ]

  json_block = json.dumps(matrix, indent=2, sort_keys=False) + "\n"

  return "\n".join(
    [
      "# Attack Damage Matrix",
      "",
      "This file is auto-generated by `update_damage_matrix_md.py` from the in-browser editor.",
      "",
      f"- Updated (UTC): `{updated}`",
      "- Source of truth: the JSON block at the bottom of this file.",
      "",
      "## Base Damage (Quick View)",
      "",
      *base_table_lines,
      "",
      "## Damage Matrix JSON",
      "",
      "<!-- BEGIN_DAMAGE_MATRIX_JSON -->",
      "```json",
      json_block.rstrip("\n"),
      "```",
      "<!-- END_DAMAGE_MATRIX_JSON -->",
      "",
    ]
  )


def atomic_write_text(path: str, text: str) -> None:
  folder = os.path.dirname(os.path.abspath(path)) or "."
  os.makedirs(folder, exist_ok=True)

  fd, tmp_path = tempfile.mkstemp(prefix=os.path.basename(path) + ".", suffix=".tmp", dir=folder)
  try:
    with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
      f.write(text)
    os.replace(tmp_path, path)
  finally:
    try:
      if os.path.exists(tmp_path):
        os.remove(tmp_path)
    except OSError:
      pass


def main() -> int:
  parser = argparse.ArgumentParser(description="Write damage-matrix.md from JSON provided via stdin.")
  parser.add_argument("--output", default="damage-matrix.md", help="Path to write (default: damage-matrix.md)")
  args = parser.parse_args()

  raw = sys.stdin.read()
  if not raw.strip():
    print("Expected JSON on stdin.", file=sys.stderr)
    return 2

  try:
    candidate = json.loads(raw)
  except json.JSONDecodeError as exc:
    print(f"Invalid JSON: {exc}", file=sys.stderr)
    return 2

  validated = validate_damage_matrix(candidate)
  if not validated:
    print("Invalid damage matrix shape.", file=sys.stderr)
    return 2

  markdown = render_markdown(validated)
  atomic_write_text(args.output, markdown)
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
