"""
Utility to append the latest DEBATE.md content into EDITS.md's pending queue.

Usage:
  python scripts/queue_debate_for_agent_c.py

This simply wraps the current DEBATE.md text in a fenced block and appends it
under a "Pending import from DEBATE.md" marker in EDITS.md so the Builder can
apply it later when tools are available.
"""

from __future__ import annotations

from datetime import datetime, timezone
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEBATE_PATH = ROOT / "DEBATE.md"
EDITS_PATH = ROOT / "EDITS.md"


def main() -> None:
    if not DEBATE_PATH.exists():
        raise SystemExit("DEBATE.md not found.")
    debate_text = DEBATE_PATH.read_text(encoding="utf-8")
    handoff_match = re.search(
        r"## Handoff to Builder\n([\s\S]+)", debate_text, re.MULTILINE
    )
    if not handoff_match:
        raise SystemExit("No 'Handoff to Builder' section found in DEBATE.md.")
    debate_text = handoff_match.group(0).strip()

    timestamp = datetime.now(timezone.utc).isoformat()
    payload = (
        "\n\n"
        "### Pending import from DEBATE.md (autogenerated)\n"
        f"- Captured: {timestamp}\n\n"
        "```\n"
        f"{debate_text}\n"
        "```\n"
    )

    EDITS_PATH.write_text(
        EDITS_PATH.read_text(encoding="utf-8").rstrip() + payload,
        encoding="utf-8",
    )
    print("Appended DEBATE.md content into EDITS.md pending queue.")


if __name__ == "__main__":
    main()
