from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
import os
from pathlib import Path
import subprocess
import sys

from agents import Runner

from multi_agents import build_navigator_agents, DEFAULT_MODEL


REPO_ROOT = Path(__file__).resolve().parent
MINITREE_PATH = REPO_ROOT / "MINITREE.md"
TREEPATH_PATH = REPO_ROOT / "TREEPATH.md"
SHIP_LOG_PATH = REPO_ROOT / "SHIP_LOG.md"
NAVIGATOR_PERSONA_PATH = REPO_ROOT / "PERSONAS_NAVIGATOR.md"


@dataclass
class TreePathEntry:
    name: str
    visited: bool


def _load_minitree_names() -> list[str]:
    names: list[str] = []
    for line in MINITREE_PATH.read_text(encoding="utf-8").splitlines():
        line = (line or "").strip()
        if line.startswith("- "):
            name = line[2:].strip()
            if name:
                names.append(name)
    return names


def _parse_treepath_entries(text: str) -> list[TreePathEntry]:
    entries: list[TreePathEntry] = []
    for raw in text.splitlines():
        line = (raw or "").strip()
        if not line or line.startswith("#") or line.startswith("<!--"):
            continue
        if line.startswith("- "):
            line = line[2:].strip()
        visited = False
        if line.startswith("X "):
            visited = True
            line = line[2:].strip()
        if line:
            entries.append(TreePathEntry(name=line, visited=visited))
    return entries


def _render_treepath(entries: list[TreePathEntry]) -> str:
    lines: list[str] = ["# TREEPATH", ""]
    for entry in entries:
        prefix = "X " if entry.visited else ""
        lines.append(f"- {prefix}{entry.name}")
    return "\n".join(lines).rstrip() + "\n"


def _ensure_treepath_initialized(*, reset: bool = False) -> list[TreePathEntry]:
    names = _load_minitree_names()
    if reset or not TREEPATH_PATH.exists():
        return [TreePathEntry(name=n, visited=False) for n in names]

    existing = _parse_treepath_entries(TREEPATH_PATH.read_text(encoding="utf-8"))
    if not existing:
        return [TreePathEntry(name=n, visited=False) for n in names]

    # Ensure it stays aligned with MINITREE order (append any newly added nodes at the end).
    existing_map = {e.name: e.visited for e in existing}
    return [TreePathEntry(name=n, visited=bool(existing_map.get(n, False))) for n in names]


def _update_navigator_persona_from_minitree() -> str:
    persona = NAVIGATOR_PERSONA_PATH.read_text(encoding="utf-8") if NAVIGATOR_PERSONA_PATH.exists() else ""
    start_marker = "<!-- MINITREE_START -->"
    end_marker = "<!-- MINITREE_END -->"
    names = _load_minitree_names()
    minitree_body = "\n".join(f"- {n}" for n in names)

    if start_marker in persona and end_marker in persona:
        before, rest = persona.split(start_marker, 1)
        _, after = rest.split(end_marker, 1)
        next_persona = (before + start_marker + "\n" + minitree_body + "\n" + end_marker + after).rstrip() + "\n"
    else:
        next_persona = (persona.rstrip() + "\n\n## MINITREE (autogenerated)\n" + start_marker + "\n" + minitree_body + "\n" + end_marker + "\n").lstrip()

    return next_persona


def _tree_cli(*args: str) -> str:
    completed = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "tree_cli.py"), *args],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=60,
    )
    stdout = (completed.stdout or "").strip()
    stderr = (completed.stderr or "").strip()
    if completed.returncode == 0:
        return stdout
    if stdout and stderr:
        return f"{stdout}\n{stderr}"
    return stdout or stderr or f"[tree_cli failed: exit={completed.returncode}]"


def _append_ship_log(lines: list[str], *, reset: bool = False) -> None:
    if reset or not SHIP_LOG_PATH.exists():
        SHIP_LOG_PATH.write_text("# SHIP LOG\n\n", encoding="utf-8")
    existing = SHIP_LOG_PATH.read_text(encoding="utf-8")
    blob = "\n".join(lines).rstrip() + "\n"
    SHIP_LOG_PATH.write_text(existing.rstrip() + "\n\n" + blob, encoding="utf-8")


def _fallback_quip(node_name: str) -> str:
    # Deterministic, offline-friendly quip.
    bits = sum(ord(ch) for ch in node_name) % 5
    options = [
        "A classic. Humanity: still iterating.",
        "Somewhere, an ancestor is nodding approvingly.",
        "This one walks so a thousand overcomplicated successors can sprint.",
        "If this breaks, the whole timeline gets weird.",
        "Finally: a node with the audacity to exist.",
    ]
    return options[bits]


def _navigator_quip(node_name: str, node_block: str, *, model: str, mode: str, use_llm: bool) -> str:
    if not use_llm:
        return _fallback_quip(node_name)
    if not os.environ.get("OPENAI_API_KEY"):
        return _fallback_quip(node_name)
    try:
        agents = build_navigator_agents(model=model, mode=mode)
        prompt = (
            "Write 1–2 short funny lines about this tech node. "
            "Keep it light, no cruelty. No markdown.\n\n"
            f"Node name: {node_name}\n\n"
            f"TREE.md block:\n{node_block}\n"
        )
        result = Runner.run_sync(agents.navigator, input=prompt, max_turns=1)
        text = (result.final_output or "").strip()
        return text or _fallback_quip(node_name)
    except Exception:
        return _fallback_quip(node_name)


def start_navigation(
    start_node: str,
    *,
    limit: int | None = None,
    mode: str = "agent",
    model: str = DEFAULT_MODEL,
    use_llm: bool = False,
    reset_treepath: bool = False,
    reset_ship_log: bool = False,
    dry_run: bool = False,
) -> None:
    persona_next = _update_navigator_persona_from_minitree()
    entries = _ensure_treepath_initialized(reset=reset_treepath)

    if not dry_run:
        NAVIGATOR_PERSONA_PATH.write_text(persona_next, encoding="utf-8")
        TREEPATH_PATH.write_text(_render_treepath(entries), encoding="utf-8")
        if reset_ship_log:
            SHIP_LOG_PATH.write_text("# SHIP LOG\n\n", encoding="utf-8")

    normalized_start = start_node.strip()
    if not normalized_start:
        raise SystemExit("start_node is empty")

    try:
        start_idx = next(i for i, e in enumerate(entries) if e.name == normalized_start)
    except StopIteration:
        raise SystemExit(f'Start node not found in TREEPATH.md: "{normalized_start}"')

    visited = 0
    for idx in range(start_idx, len(entries)):
        entry = entries[idx]
        if entry.visited:
            continue
        if limit is not None and visited >= limit:
            break

        node_name = entry.name
        node_block = _tree_cli("get-node", node_name)
        supernode = _tree_cli("get-supernode", node_name)
        upstream = _tree_cli("get-upstream", node_name)
        downstream = _tree_cli("get-downstream", node_name)
        resources = _tree_cli("get-resources", node_name)

        # Determine next unvisited node for the "going to ..." line.
        next_node = None
        for j in range(idx + 1, len(entries)):
            if not entries[j].visited:
                next_node = entries[j].name
                break

        ts = datetime.now(timezone.utc).isoformat()
        log_lines: list[str] = [
            f"## {node_name}",
            f"- Timestamp: {ts}",
            "",
            f'Navigator: going to {node_name}',
            "",
            "### Stats",
            f"- Supernode: {supernode or '(none)'}",
            f"- Upstream: {upstream or '(none)'}",
            f"- Downstream: {downstream or '(none)'}",
            f"- Resources: {resources or '(none)'}",
            "",
            "### TREE.md Block",
            "```",
            node_block.strip(),
            "```",
            "",
            f"Navigator: {_navigator_quip(node_name, node_block, model=model, mode=mode, use_llm=use_llm)}",
        ]
        if next_node:
            log_lines.append(f"Navigator: going to {next_node}")

        if dry_run:
            sys.stdout.write("\n".join(log_lines).rstrip() + "\n")
        else:
            _append_ship_log(log_lines, reset=(reset_ship_log and visited == 0))
            entries[idx].visited = True
            TREEPATH_PATH.write_text(_render_treepath(entries), encoding="utf-8")

        visited += 1


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Navigator controller (TREEPATH/SHIP_LOG).")
    parser.add_argument("start_node", help="Node name to start at (must exist in TREEPATH.md).")
    parser.add_argument("--mode", choices=["agent", "chat"], default="agent")
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--use-llm", action="store_true", help="Use the Navigator LLM for humor (requires network + OPENAI_API_KEY).")
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--reset-treepath", action="store_true", help="Reset TREEPATH.md to a fresh copy of MINITREE.md.")
    parser.add_argument("--reset-ship-log", action="store_true", help="Reset SHIP_LOG.md before writing the first visited node.")
    parser.add_argument("--dry-run", action="store_true", help="Do not write TREEPATH.md or SHIP_LOG.md.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> None:
    args = parse_args(argv)
    start_navigation(
        args.start_node,
        limit=args.limit,
        mode=args.mode,
        model=args.model,
        use_llm=args.use_llm,
        reset_treepath=args.reset_treepath,
        reset_ship_log=args.reset_ship_log,
        dry_run=args.dry_run,
    )


if __name__ == "__main__":
    main(sys.argv[1:])
